# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /posts/:title
timezone: America/Bogota

# Setup
title: Federico Garcia
tagline: ''
description: 'Ideas and stories of a journeyman'
url: http://federicogarcia.me
tracking_code: 'UA-61072413-1'

author:
  name: 'Federico Garcia'
  url: https://twitter.com/thelaxtsamurai
  twitter: thelaxtsamurai

exclude:
  - Gemfile
  - Gemfile.lock
  - bin

gems:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

sass:
  sass_dir: _scss
  style: :compressed

paginate: 5

# Custom vars
disqus_shortname: thelaxtsamurai
